package com.travel.model;
// Generated 4-set-2016 14.14.06 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String slug;
	private String name;
	private String description;
	@JsonBackReference
	private Set travels = new HashSet(0);

	public Category() {
	}

	public Category(String slug, String name, String description, Set travels) {
		this.slug = slug;
		this.name = name;
		this.description = description;
		this.travels = travels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTravels() {
		return this.travels;
	}

	public void setTravels(Set travels) {
		this.travels = travels;
	}

}
