package com.travel.model;
// Generated 4-set-2016 14.14.06 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable, UserDetails {

	private Integer id;
	private Profile profile;
	private String username;
	private String email;
	private String password;
	private Date createdAt;
	private Date updatedAt;
	@JsonBackReference
	private Set travels = new HashSet(0);
	 /* Spring Security related fields*/
	@JsonBackReference
    private List<Role> authorities;
	@JsonBackReference
    private boolean accountNonExpired = true;
	@JsonBackReference
    private boolean accountNonLocked = true;
	@JsonBackReference
    private boolean credentialsNonExpired = true;
	@JsonBackReference
    private boolean enabled = true;

	public User() {
	}

	public User(Profile profile, String username, String email, String password, Date createdAt, Date updatedAt,
			Set travels) {
		this.profile = profile;
		this.username = username;
		this.email = email;
		this.password = password;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.travels = travels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getTravels() {
		return this.travels;
	}

	public void setTravels(Set travels) {
		this.travels = travels;
	}
	
	public List<Role> getAuthorities() {
	        return authorities;
	    }
	
	    public void setAuthorities(List<Role> authorities) {
	        this.authorities = authorities;
	    }
	    public boolean isAccountNonExpired() {
	        return accountNonExpired;
	    }
	    public void setAccountNonExpired(boolean accountNonExpired) {
	        this.accountNonExpired = accountNonExpired;
	    }
	    public boolean isAccountNonLocked() {
	        return accountNonLocked;
	    }
	    public void setAccountNonLocked(boolean accountNonLocked) {
	        this.accountNonLocked = accountNonLocked;
	    }
	    public boolean isCredentialsNonExpired() {
	        return credentialsNonExpired;
	    }
	    public void setCredentialsNonExpired(boolean credentialsNonExpired) {
	        this.credentialsNonExpired = credentialsNonExpired;
	    }
	    public boolean isEnabled() {
	        return enabled;
	    }
	    public void setEnabled(boolean enabled) {
	        this.enabled = enabled;
	    }

}
